name: Slacktion

on:
  # Uncomment the below to run this action every 5 minutes
  # schedule:
  #   - cron: '*/5 * * * *'

  # Run this action manaully
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  check-prs:
    name: Notify Slack Channel for Old PRs
    runs-on: ubuntu-latest

    steps:
      - name: Notify Slack
        id: notify
        uses: actions/github-script@v7
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          script: |
            const today = new Date()

            // Get all open PRs targeting `main`
            const { data } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              base: 'main'
            })

            // Filter out Dependabot, Actions, and PRs not 1/3/5 days old
            const offending = data.filter(
              (pr) =>
                pr.user.login !== 'github-actions[bot]' &&
                pr.user.login !== 'dependabot[bot]' &&
                pr.head.ref.includes('releases') &&
                pr.draft === false &&
                [0, 1, 3, 5].includes(
                  Math.floor(
                    (today.getTime() - new Date(pr.created_at).getTime()) /
                      (1000 * 3600 * 24)
                  )
                )
            )

            core.info(`Found ${offending.length} offending PRs`)
            if (offending.length === 0) return

            // Use the Slack Block Kit to make a nice, formatted message
            // https://app.slack.com/block-kit-builder
            const body = {
              blocks: [
                {
                  type: 'header',
                  text: {
                    type: 'plain_text',
                    text: ':alert: Aging PR Alert! :alert:',
                    emoji: true
                  }
                },
                {
                  type: 'section',
                  text: {
                    type: 'plain_text',
                    text: 'The following PRs are still open! Please update them or close them!'
                  }
                },
                {
                  type: 'divider'
                },
                {
                  type: 'rich_text',
                  elements: [
                    {
                      type: 'rich_text_list',
                      style: 'bullet',
                      elements: offending.map((pr) => ({
                        type: 'rich_text_section',
                        elements: [
                          {
                            type: 'text',
                            text: `@${pr.user.login} - `
                          },
                          {
                            type: 'link',
                            url: pr.html_url,
                            text: pr.title
                          },
                          {
                            type: 'text',
                            text: ` - ${Math.floor(
                              (today.getTime() - new Date(pr.created_at).getTime()) /
                              (1000 * 3600 * 24)
                            )} days`
                          }
                        ]
                      }))
                    }
                  ]
                }
              ]
            }

            fetch(process.env.SLACK_WEBHOOK_URL, {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify(body)
            })
